server:
  port: 9090
eureka:
  instance:
    hostname: eureka-server
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka
    register-with-eureka: false
    fetch-registry: false